version: '3.8'

services:
  nginx:
    image: nginx:1.20.0-alpine
    container_name: html-studio-nginx
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks: 
      - html-studio

networks:
  html-studio:
    driver: bridge
